# Single Neuron Backpropogation using Sigmoid #

In [34]:
import numpy as np
import math 
def sigmoid(z: float) -> float: 
    result = 1/(1+ math.exp(-z)) 
    return result 

def sigmoid_gradient(z: float) -> float: 
    s = sigmoid(z)
    return s * (1 - s)  

def train_neuron(features: np.ndarray, labels: np.ndarray, initial_weights: np.ndarray, initial_bias: float, learning_rate: float, epochs: int) -> (np.ndarray, float, list[float]):
    weights = initial_weights.copy()
    bias = initial_bias
    mse_values = []
    for epoch in range(epochs):
        probabilities = []
        gradient_bias = 0
        gradient_weight = np.zeros_like(weights)
        for i in range(len(features)):
            weighted_sum = np.dot(features[i],weights) + bias
            probabilities.append(sigmoid(weighted_sum)) 
            error = 2 * (sigmoid(weighted_sum) - labels[i])
            gradient_bias += (error * sigmoid_gradient(weighted_sum))
            gradient_weight += (error * sigmoid_gradient(weighted_sum) * features[i])
        weights = weights - (learning_rate * gradient_weight)/len(features)
        bias = bias - (learning_rate * gradient_bias)/len(features)
        mse = np.mean(((labels - np.array(probabilities)) ** 2))
        mse_values.append(round(mse,4))
    updated_weights = np.round(weights, 4)
    updated_bias = round(bias, 4)
    return updated_weights, updated_bias, mse_values
train_neuron(features = np.array([[1.0, 2.0], [2.0, 1.0], [-1.0, -2.0]]), labels = np.array([1, 0, 0]), initial_weights = np.array([0.1, -0.2]), initial_bias = 0.0, learning_rate = 0.1, epochs = 2)

[0.425557483188341]
[1 0 0]
gradient_weight [-0.2808545  -0.56170899]
[0.425557483188341, 0.5]
[1 0 0]
gradient_weight [ 0.2191455  -0.31170899]
[0.425557483188341, 0.5, 0.574442516811659]
[1 0 0]
gradient_weight [-0.06170899 -0.87341798]
[0.4383038875560721]
[1 0 0]
gradient_weight [-0.27657196 -0.55314393]
[0.4383038875560721, 0.5062233116446542]
[1 0 0]
gradient_weight [ 0.22957292 -0.30007148]
[0.4383038875560721, 0.5062233116446542, 0.5575887575621814]
[1 0 0]
gradient_weight [-0.04552301 -0.85026335]


(array([ 0.1036, -0.1425]), -0.0167, [0.3033, 0.2942])